create database TECNICA;
use TECNICA;

CREATE TABLE CLIENTE(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idGrupo INT NOT NULL,
nombre VARCHAR(30) NOT NULL,
cif VARCHAR(30) NOT NULL,
direccion VARCHAR(100) NOT NULL
);

CREATE TABLE GRUPO(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL
);

ALTER TABLE CLIENTE ADD FOREIGN KEY (idGrupo) REFERENCES GRUPO (id);


/*============Insert Defualt============*/
INSERT INTO GRUPO(nombre) VALUE(1);
INSERT INTO GRUPO(nombre) VALUE(2);